set_property SRC_FILE_INFO {cfile:C:/Users/njs82/Documents/xilinx_projects/ck_div/ck_div.srcs/constrs_1/imports/xilinx_projects/Basys3_Master.xdc rfile:../../../ck_div.srcs/constrs_1/imports/xilinx_projects/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports ck]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {reset}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {z}]
