webtalk_init -webtalk_dir /home/nick/ECEC302/W3/Lab/adder_project/adder_project.sim/sim_1/behav/xsim/xsim.dir/adder_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 16 13:44:24 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e6e3c9b7-fdf1-49bf-84f8-f15a7c147498" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6ad1c3d675234b63b52c494da7288f45" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2870.651 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2300 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.07_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114824_KB" -context "xsim\\usage"
webtalk_transmit -clientid 859819663 -regid "" -xml /home/nick/ECEC302/W3/Lab/adder_project/adder_project.sim/sim_1/behav/xsim/xsim.dir/adder_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/nick/ECEC302/W3/Lab/adder_project/adder_project.sim/sim_1/behav/xsim/xsim.dir/adder_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/nick/ECEC302/W3/Lab/adder_project/adder_project.sim/sim_1/behav/xsim/xsim.dir/adder_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
