# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/xoepe/Documents/ECEC302/HW8/accumulator/accumulator.srcs/sources_1/ip/c_accum_0/c_accum_0.xci
# IP: The module: 'c_accum_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xoepe/Documents/ECEC302/HW8/accumulator/accumulator.srcs/sources_1/ip/c_accum_0/c_accum_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_accum_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/xoepe/Documents/ECEC302/HW8/accumulator/accumulator.srcs/sources_1/ip/c_accum_0/c_accum_0.xci
# IP: The module: 'c_accum_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xoepe/Documents/ECEC302/HW8/accumulator/accumulator.srcs/sources_1/ip/c_accum_0/c_accum_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_accum_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
